version: '3.8'

services: 
    app:
        build: 
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes: 
            - ./src/:/var/www/html
        environment: 
            - DB_CONNECTION=postgres
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=${DB_NAME}
            - DB_USERNAME=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
    
    web:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports: 
            - ${WEB_PORT}:80
        depends_on:
            - app
        volumes: 
            - ./src/:/var/www/html
    
    db:
        build: 
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        ports: 
            - ${DB_PORT}:5432
        environment: 
            POSTGRES_DATABASE: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            TZ: 'Asia/Tokyo'
        volumes: 
            - ./docker/postgres/init:/docker-entrypoint-initdb.d